greeting: Hello TAP!

spring:
  application:
    name: payment-calculator

info:
  app:
    name: Payment Calculator

management:
  endpoint:
    health:
      show-details: always
    info:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: https://api.honeycomb.io/v1/traces
      headers:
        "x-honeycomb-team": "xxxxxxx"
